Replaced .flat() with alternative
vvo/next-iron-session pull request #235
Opened 2020-10-08 13:57 UTC by humayunj

Replaced use of flat method with alternative to support previous version of node as NextJs, specially v10.13.0 [https://nextjs.org/docs#system-requirements](url).

Alternative supports only one level deep flattening of cookie array, because I think that's the type of res.getHeader('set-cookie')  and it doesn't get any deeper.

2020-10-08 14:05 UTC, vvo requested changes
If we want to merge this, we will also have to setup GitHub action to do tests on different versions of Node.js so if someone rewrites this at some point, they'll get errors.

Do you have experience with GitHub actions? Otherwise, I'll have a look.

2020-10-08 14:05 UTC, vvo commented on lib/index.js
> +      const existingSetCookie = [res.getHeader('set-cookie') || []].reduce((acc, val) => acc.concat(val), []); //Flat array
could you create a flattenArray() function instead in the same file (at the bottom) and use it?

2020-10-08 20:40 UTC, humayunj commented
> 
> 
> If we want to merge this, we will also have to setup GitHub action to do tests on different versions of Node.js so if someone rewrites this at some point, they'll get errors.
> 
> Do you have experience with GitHub actions? Otherwise, I'll have a look.

Is it necessary to setup up tests for multiple node versions, why not just lower the tests node version to 10.X Or am I missing something?

2020-10-15 07:55 UTC, vvo commented
> Is it necessary to setup up tests for multiple node versions, why not just lower the tests node version to 10.X Or am I missing something?

Since Node 10, 12, 14 are major versions, there's a possibility something will break. Since users of next-iron-session are using different Node.js versions then IF we start saying it's compatible with Node 10, we should verify it's still compatible with 12 and 14.

WDYT?

2020-11-05 13:03 UTC, vvo commented
Hey there, this is now solved and next-iron-session works on Node 10, 12, 14, 15 (and tested)

Thanks for noticing this and the effort, greatly appreciated 🙏

2020-11-05 13:03 UTC, closed without merging