allow cookie option overrides on save
vvo/next-iron-session pull request #246
Opened 2020-10-16 23:48 UTC by jrobber

Save now takes an optional parameter that is another set of cookie options.

If there are any there they override the default options passed in during initial creation.

Use Case:
* I apply a basic session to a user
* User logs into facebook or other provider
* Facebook dictates a max age/expires length
-> when I update my session I can also update maxAge to match what facebook provided

Also, this generic change should support a whole host of other scenarios and cookie management.

2020-11-05 13:07 UTC, vvo requested changes
Hi there, thanks for the suggestion, it makes sense. So that I can accept this PR we would need:
- API documentation update
- typings update
- add a simple test

Let me know which task you think is OK and which one you'd like help with, thanks

2020-11-05 13:07 UTC, vvo commented on package.json
> +    "prepare": "yarn build",
Hi there, any comment you can provide about this change?

2020-11-05 13:07 UTC, vvo commented on lib/index.js
> +    async save(cookieOptionsOverrides = {}) {
Let's use the same option name as init: `.save({cookieOptions: {...}})`, can you make this change?

2020-12-03 20:50 UTC, pedrojimenezp commented
@vvo @jrobber  Maybe I can continue the work of this PR if you don't have time.
I can work on the fixes/task you are asking for so you can merge it soon.

2020-12-07 20:27 UTC, vvo commented
@pedrojimenezp yes you can move on with the PR, appreciated!

2021-04-09 14:25 UTC, vvo commented
@jrobber @pedrojimenezp closing for now, but feel free to reopen a PR / answer to comments I added

2021-04-09 14:25 UTC, closed without merging